> ## Make a copy of this notebook (File menu -> Make a Copy...)

### Homework Question 1

By giving examples, explain all meanings of the `@` operator we covered in lab. You may use the examples from the lab. You should include both code and text explanation.

In [19]:
import numpy as np
v = np.array([[5],[3],[-2]])
x = np.array([1,2,3])

A = np.arange(1,10).reshape((3,3))
B = np.array([[3,1,1],[2,2,4],[5,7,1]]) 
#print(A)
#print(v)
print(x@v)
print(x@A)
print(A@v)
print(A@B)
print(5*A[:,0]+3*A[:,1]-2*A[:,2])
print(np.array([A[0]@v,A[1]@v,A[2]@v]))

[5]
[30 36 42]
[[ 5]
 [23]
 [41]]
[[22 26 12]
 [52 56 30]
 [82 86 48]]
[ 5 23 41]
[[ 5]
 [23]
 [41]]


The first printed statement demonstrates what happens with a dot product between a row vector and a column vector; this results in a single value because the multiplication of vectors with $1\times 3$ and $3\times 1$ dimensions respectively will create a matrix of size $1\times 1$. The second statement shows how the dot product between a $1\times 3$ row vector and a $3\times 3$ matrix prints out a row vector of dimensions $1\times 3$. The third statement shows the dot product between a $3\times 3$ matrix and a $3\times 1$ column vector, and how it creates a column vector of dimensions $1\times 3$. The fourth statement demonstrates the dot product between two $3\times 3$ matrices that results in another $3\times 3$ matrix. The fifth statement  is essentially creating a row vector by multiplying each column in $A$ by every value in column vector $v$ and summing these columns together to create a single row vector. Finally, the sixth statement basically does the same thing as the third statement; it takes every row of $A$ and makes the dot product between these rows and column vector $v$ each value in the final column vector.

### Homework Question 2

Explain how Questions 3 and 6 from the lab demonstrate the *column* and *row* pictures of matrix multiplication respectively. Be sure to use the terms *dot product* and *linear combination* in your answer. Again, use both text and code.

In [25]:
print(A)
print(B)
print(A@B)
print(np.array([A@B[:,0], A@B[:,1], A@B[:,2]]).T)

c1 = B[0,0]*A[:,0] + B[1,0]*A[:,1] + B[2,0]*A[:,2]
c2 = B[0,1]*A[:,0] + B[1,1]*A[:,1] + B[2,1]*A[:,2]
c3 = B[0,2]*A[:,0] + B[1,2]*A[:,1] + B[2,2]*A[:,2]
print(np.array([ c1,c2,c3 ]).T)

print((A[1]@B[:,2]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 1 1]
 [2 2 4]
 [5 7 1]]
[[22 26 12]
 [52 56 30]
 [82 86 48]]
[[22 26 12]
 [52 56 30]
 [82 86 48]]
[[22 26 12]
 [52 56 30]
 [82 86 48]]
30


Each of the first three print statements demonstrate how to take the dot product between matrices $A$ and $B$. The first print statement is the simplest way to get the dot product of these matrices by directly multiplying them. The second print statement demonstrates how we can compute the dot product between $A$ and each individual column of $B$ in order to get a matrix whose rows are the columns of the dot product of $A$ and $B$. By transposing this matrix, we receive the same result as the first print statement because swapping the $(i,j)$ value for the $(j,i)$ value essentially just makes each row into a column and vice versa. Similarly, the third print statement demonstrates the exact same idea, except it explicitly states the process for finding each value of the resulting matrix, by multiplying individual values in $B$ by each column in $A$ (making the final matrix a linear combination using values in matrix $B$ as the weights multiplied against matrix $A$). The final print statement shows how we can extract a single value from a matrix; if we want to retrieve the second row, third column, we can compute a dot product using the second row of $A$ and the third column of $B$ to find this value.

### Homework Question 3

Submit your answers to Question 10 from the lab. You should typeset all matrices in LaTeX as part of your text below. Be sure to write complete sentences and full explanations.

\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 1\\
0 & 1 & 0\\
1&0&1\\
1&1&1\\
1&1&0\\
0&0&1\\
1&0&1\\
\end{bmatrix}	
* 2) $A^T \times A$  
* 2a) The size of this matrix is $3\times3$	
* 2b) Rows and columns represent the different organizations.
* 2c) N/A
* 2d) The ith value on the diagonal tells us the amount of people who are in that organization. In order to compute this entry, we essentially just tallied up the numbers for each column (representing each organization)
* 2e) if $i$ is not equal to $j$, then $(i,j)$ represents the the amount of people who are in both the $ith$ and the $jth$ organization. This makes sense because when we compute the dot product between $A^T$ and $A$ and do this on $A^T$'s ith row and $A$'s jth column, we are only going to get non zero values within each row/column when both corresponding values in the row and column are equal to one, meaning that they are both in that organization. Thus, this represents the sum of all people in both organizations.
* 2f) $(i,j)$ and $(j,i)$ are the same because they represent the same two organizations, just in opposite order.
* 5a) The significance of nonzero nondiagonal entries $(i,j)$ represent the amount of organizations that the $ith$ row person shares with the $jth$ column person.
* 5b) Compute the number for each of the 8 people:
\begin{bmatrix}
4&6&3&6&7&6&4&6\\
\end{bmatrix}

### Homework Question 4

Other than Paul Revere, pick one of the central actors identified at the end of the lab. Do some research on that person and submit a paragraph describing them and their role in the Revolutionary War. Submit this in the last textbox below, again using Markdown to format your answers. Be sure to cite your sources!

I selected William Molineux and analyzed his role in the Revolutionary War. Although he was clearly one of the war's most prominent participants, with 154 connections within the network of rebels, he was not nearly as recognizable as some of the other members on this list. Upon doing some research, I found that the reason for this was that he had actually died before the Revolutionary War had even begun. Due to this, as well as his revolutionary ideas that were considered radical for the time by some of his colleagues, he is largely unmentioned for his contributions in history. However, by leading boycotts and large demonstrations against the Townshend Acts, and even by becoming one of the organizers of the Boston Tea Party, he certainly did not play an insignificant role in the rising tension between Great Britain and the American colonies that spilled over into war.

Sources:$\newline$
https://en.wikipedia.org/wiki/William_Molineux $\newline$
https://www.nps.gov/articles/000/william-molineux.htm

### Homework Question 5

Explain what the following code does, then rewrite it in a more NumPy-ish way. See Lab 1 for hints! You should be able to get the same result with one line of code! Test your code by taking any $4\times 5$ matrix and checking that your code and this routine give the same answer on it.

```python
def addrows(A):
    rows,cols = A.shape
    
    rowsum = np.zeros(rows)
    
    for row in range(rows):
        for col in range(cols):
            rowsum[row] += A[row,col]
    
    return rowsum
```

This code basically just takes the sum of all the rows and places these values into a row vector.

In [26]:
test = np.array([[3,1,1,3],[2,2,4,5],[5,7,1,2]])                          
#def addrows(A):
#    rows,cols = A.shape
#
#    rowsum = np.zeros(rows)
#
#    for row in range(rows):
#        for col in range(cols):
#            rowsum[row] += A[row,col]
#
#    return rowsum
def addrows(A):
    return(A.sum(axis=1))

print(test)
print(addrows(test))

[[3 1 1 3]
 [2 2 4 5]
 [5 7 1 2]]
[ 8 13 15]


### Homework Question 6

Write routines that take a matrix and return results as follows. It is also perfectly fine (perhaps better!) to give single lines of code that achieve the same result instead of routines. This is possible with all these, but much easier for second and third than the first.

* *swaprows(A,i,j)* should take an array and return the same array, but with rows *i* and *j* swapped.
* *rowmult(A,i,c)* should take an array, a row number *i* and a constant *c*, and return the same array, but with row *i* multiplied by *c*.
* *rowaddmult(A,i,j,c)* should take an array, row numbers *i* and *j*, and a constant *c*, and return the same array, but with *c* multiplied by row *i* added to row *j*.

As always, show examples of your code. Use a $4\times 5$ array of your choice.

> **Note:** We will use these routines/lines of code extensively in the coming labs. Get them right!

In [4]:
def swaprows(A,i,j):
    A[[i, j],:] = A[[j, i],:] 
def rowmult(A,i,c):
    A[i] = A[i]*c
def rowaddmult(A,i,j,c):
    A[j] = A[i]*c + A[j]
    
A = np.array([[3,1,1,3],[2,2,4,5],[5,7,1,2]])                          
print(A)
swaprows(A,1,2)
print(A)
rowaddmult(A,2,2,3)
print(A)

[[3 1 1 3]
 [2 2 4 5]
 [5 7 1 2]]
[[3 1 1 3]
 [5 7 1 2]
 [2 2 4 5]]
[[ 3  1  1  3]
 [ 5  7  1  2]
 [ 8  8 16 20]]
