> ## Make a copy of this notebook (File menu -> Make a Copy...)

### Homework Question 1
Consider the same situation as in Question 15 from the lab, but on a pentagon instead of a square. That is, there are five corners instead of four. Show that the corresponding Markov chain is not periodic, and that its transition matrix is regular.

Here, after taking A^k @ v0 for a variety of initial vectors (one that starts in corner A, one that has equal probability of starting in any corner, and one with an unequal distribution of starting probabilities), we can see that regardless of the initial state, with a high enough exponent value, vn becomes a matrix of all 0.2 values. When we do different exponents that vary by 1, we still get the same matrix, demonstrating it is not periodic since it will eventually reduce to the same probabilities. We also know the transition matrix is regular because after taking various different exponents with A, they all get the same matrix that is column stochastic and each element is non-zero.

In [1]:
import numpy as np
A = np.array([[0,0.5,0,0,0.5],[0.5,0,0.5,0,0],[0,0.5,0,0.5,0],[0,0,0.5,0,0.5],[0.5,0,0,0.5,0]])
#we start in node A with V
v0 = np.array([1.,0,0,0,0])
v0 = np.array([0.2,0.2,0.2,0.2,0.2])
v0 = np.array([0.1,0.15,0.2,0.25,0.3])
v200 = np.linalg.matrix_power(A,200)@v0
v201 = np.linalg.matrix_power(A,201)@v0
v202 = np.linalg.matrix_power(A,202)@v0
v203 = np.linalg.matrix_power(A,203)@v0
v204 = np.linalg.matrix_power(A,204)@v0

print(A)
print(v0)
print(v200)
print(v201)
print(v202)
print(v203)
print(v204)

[[0.  0.5 0.  0.  0.5]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.5 0. ]]
[0.1  0.15 0.2  0.25 0.3 ]
[0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2]
[0.2 0.2 0.2 0.2 0.2]


### Homework Question 2
Consider a Markov chain with transition matrix given by the following code:
  ```python
  A= np.array([
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.25  ],
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.75  ],
               [ 0.5   ,  0.3333,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.6667,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.3333,  0.5   ,  0.75  ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.6667,  0.5   ,  0.25  ,  0.    ,  0.    ]])
   ```
  
1. Draw a state space diagram for this chain (use [this link](https://graphonline.ru/en/)). If you're having trouble putting the nodes and arrows in sensible places, you may want to do the rest of this question first.<br><br>
1. Show that this chain is periodic. What is the period?<br><br>
1. By again considering powers of this matrix, show that the seven nodes divide into three *cyclic classes*. That is, show that there are three subsets of nodes, $A$, $B$, and $C$, each with the property 'if we start at a node in a given class, we can only return to the class $p$ steps later, where $p$ is the period of the chain'. Numbering the nodes from 1 to 7, which nodes are in each cyclic class?<br><br>

It has a period of 3.
A = 6,7
B = 1,2
C = 3,4,5

In [2]:
A= np.array([
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.25  ],
               [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.5   ,  0.75  ],
               [ 0.5   ,  0.3333,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.25  ,  0.6667,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.3333,  0.5   ,  0.75  ,  0.    ,  0.    ],
               [ 0.    ,  0.    ,  0.6667,  0.5   ,  0.25  ,  0.    ,  0.    ]])
v0 = np.array([1.,0,0,0,0,0,0])
#v0 = np.array([0.14285714285,0.14285714285,0.14285714285,0.14285714285,0.14285714285,0.14285714285,0.14285714285])
#v0 = np.array([0.05,0.05,0.10,0.15,0.20,0.25])
v200 = np.linalg.matrix_power(A,200)@v0
v201 = np.linalg.matrix_power(A,201)@v0
v202 = np.linalg.matrix_power(A,202)@v0
v203 = np.linalg.matrix_power(A,203)@v0
v204 = np.linalg.matrix_power(A,204)@v0

print(A)
print(v0)
#print(v200)
#print(v201)
#print(v202)
#print(v203)
#print(v204)
for line in v200,v201,v202,v203,v204:
    print ('  '.join(map(str,line)))
    

[[0.     0.     0.     0.     0.     0.5    0.25  ]
 [0.     0.     0.     0.     0.     0.5    0.75  ]
 [0.5    0.3333 0.     0.     0.     0.     0.    ]
 [0.25   0.     0.     0.     0.     0.     0.    ]
 [0.25   0.6667 0.     0.     0.     0.     0.    ]
 [0.     0.     0.3333 0.5    0.75   0.     0.    ]
 [0.     0.     0.6667 0.5    0.25   0.     0.    ]]
[1. 0. 0. 0. 0. 0. 0.]
0.0  0.0  0.0  0.0  0.0  0.5596592157052928  0.4403407842947032
0.38991480392632216  0.6100851960736737  0.0  0.0  0.0  0.0  0.0
0.0  0.0  0.39829879781451655  0.09747870098158054  0.5042225012038988  0.0  0.0
0.0  0.0  0.0  0.0  0.0  0.5596592157052928  0.44034078429470314
0.38991480392632216  0.6100851960736738  0.0  0.0  0.0  0.0  0.0


### Homework Question 3

For this question, you will write code that generates sensible random words that are (mostly) pronounceable in English. You will do this by creating a Markov chain whose nodes are letters in English words, and whose transition probabilities are given by analyzing a large set of existing English words.<br><br>

1. You will find a set of approximately 275,000 English words in the file *en.txt*. We will use this to figure out what the probability of a letter occuring in a word is, given the previous letter. For example, if the current letter is 'q', the next letter is 'u' with very high probability. Generate the transition matrix between all 26 states (a.k.a. English letters). Here are some code snippets that might help: 
```python
      # This opens the file and prints every line.
      f = open('en.txt')
      for word in f:
         print(word)

      # After you're done with a file, close it:
      f.close()

      # Each line has an extra character at the end (the endline character). The following code strips it:
      word = word.rstrip()

      # Strings can be accessed like one-dimensional arrays:
      for i in len(word):
         print(word[i])

      # The following function will return a number correponding to the letter input.
      # e.g. testletter('a') will return 0, and testletter('z') will return 25
      import string
      def let2num(letter):
          dictionary = {letter: index for index, letter in enumerate(string.ascii_lowercase)}
          return dictionary[letter]
```
After you've written your code, check the probabilities of different letters following 'q'. This is a good indicator that your code is correct!<br><br>

In [3]:
import string
def main(file):
    A = np.zeros((26,26))
    f = open(file)
    for word in f:
        word = word.rstrip()
        getCounts(word,A)
    f.close()
    return(A)

def getCounts(word, A):
    for i in range (len(word)-1):
        A[let2num(word[i+1]),let2num(word[i])] +=1
        
def let2num(letter):
       dictionary = {letter: index for index, letter in enumerate(string.ascii_lowercase)}
       return dictionary[letter]
A = main('en.txt')
print(A)

[[2.0800e+02 6.4590e+03 1.4813e+04 4.6000e+03 1.0534e+04 2.9270e+03
  5.3920e+03 9.3570e+03 1.0521e+04 1.0560e+03 1.8010e+03 1.6576e+04
  1.2675e+04 1.1254e+04 2.5910e+03 8.6700e+03 3.8000e+01 2.4503e+04
  7.1290e+03 1.4206e+04 2.9480e+03 3.6130e+03 4.0080e+03 6.0000e+02
  1.2240e+03 2.0030e+03]
 [8.5970e+03 1.5180e+03 1.0000e+01 3.5100e+02 2.1870e+03 3.7000e+01
  1.5400e+02 2.5300e+02 3.0070e+03 0.0000e+00 2.5100e+02 4.7300e+02
  3.3830e+03 7.9700e+02 3.3290e+03 1.6400e+02 0.0000e+00 2.3770e+03
  4.2000e+02 4.8200e+02 3.2760e+03 0.0000e+00 2.2600e+02 1.8000e+01
  4.5100e+02 1.6000e+01]
 [1.1180e+04 2.2200e+02 1.5520e+03 1.8900e+02 9.3680e+03 1.6000e+01
  2.5000e+01 1.0800e+02 2.0891e+04 0.0000e+00 6.5000e+01 8.3100e+02
  6.9000e+01 8.9520e+03 6.6190e+03 9.5000e+01 0.0000e+00 3.6570e+03
  7.0020e+03 1.6350e+03 3.3490e+03 0.0000e+00 6.3000e+01 3.9100e+02
  1.4250e+03 1.0000e+01]
 [6.8840e+03 2.4400e+02 4.4000e+01 1.6710e+03 2.6209e+04 1.6000e+01
  7.7000e+01 8.2000e+01 7.6820e+03 2.0000

In [8]:
def prob(A):
    ct = np.sum(A,axis = 0)
    for i in range (0, 26):
        A[:,i] = A[:,i]/ ct[i];
    return(A)
    
#print(A)
col = let2num("q")
row = let2num("u")
probs = prob(A)
print (probs[13:17,13:17])

[[0.01764019 0.1842837  0.00385796 0.        ]
 [0.05979319 0.03795708 0.11691363 0.00143062]
 [0.00522044 0.05383569 0.03840609 0.        ]
 [0.00192861 0.00133664 0.         0.        ]]


1. Since this is a large matrix, it would not be efficient to use our row-reduction code to find its eigenvalues and eigenvectors. Instead, we use a NumPy built-in function. By investigating the *np.linalg.eig(A)* function using its documentation, find the eigenvector corresponding to the eigenvalue 1 for your transition matrix. Scale it to ensure that its sum is 1!
> **Note: In general, eigenvalues and eigenvectors may be complex (i.e. contain numbers of the form $a+bi$, where $i=\sqrt{-1}$). The correct eigenvector here has no complex entries. Nonetheless, NumPy will represent the vector using its complex data type. After you're sure you have the right vector, you can cast it to real numbers by using `np.real(v)`.**


In [9]:
w, v = np.linalg.eig(probs) 
print(v[0])
w = np.real(w)
v = np.real(v)

print(w)
eig1 = v[0]
#print(eig1)

eig1 = eig1/((eig1@eig1)**.5)
#print(eig1)
#print(np.sum(eig1))
 
    
    #frequencies of each letter
    #sum across each row, and divide by the total letters. 

[ 0.29064632+0.j         -0.2567369 +0.j          0.01019684-0.05928236j
  0.01019684+0.05928236j -0.12893632-0.01285013j -0.12893632+0.01285013j
 -0.13406265-0.02212672j -0.13406265+0.02212672j  0.03796078+0.j
 -0.05259845+0.13113855j -0.05259845-0.13113855j  0.34903539+0.j
 -0.35051321+0.j         -0.02536474-0.05464059j -0.02536474+0.05464059j
 -0.01120474+0.11599301j -0.01120474-0.11599301j  0.28341647+0.j
  0.3544472 -0.08185921j  0.3544472 +0.08185921j  0.19448492-0.07829215j
  0.19448492+0.07829215j -0.2045911 +0.04687643j -0.2045911 -0.04687643j
  0.33339054+0.j         -0.34852248+0.j        ]
[ 1.         -0.41896294 -0.13612269 -0.13612269 -0.04863557 -0.04863557
  0.0799718   0.0799718   0.1153666   0.08615932  0.08615932 -0.08815771
  0.08547136  0.06522184  0.06522184 -0.02368839 -0.02368839  0.03809778
 -0.03281825 -0.03281825 -0.01159883 -0.01159883  0.01048189  0.01048189
 -0.00206151  0.00722392]


1. Explain why the entries of this eigenvector should be very close to the frequencies of each letter in the word set.<br><br>
1. Write code to check that this is indeed the case.<br><br>


In [7]:
print(probs@eig1)

[-0.08598826  0.00297592  0.05358757  0.0209346  -0.03871503 -0.00407941
  0.01341147  0.0257357  -0.00953003 -0.00042708  0.01124407  0.045994
  0.04509506  0.06627904 -0.05528456  0.0214891   0.00171068  0.02628411
  0.08969186  0.126269   -0.01392337  0.00692869  0.00723115  0.00133247
  0.00850638 -0.01183315]


1. What is the probability that the letter following 'q' is 'u'? Find some words in the list for which a letter other than 'u' follows a 'q'.<br><br>


In [10]:
def qu(file):
    qwords = []
    f = open(file)
    for word in f:
        word = word.rstrip()
        getQs(qwords,word)
    f.close()
    return(qwords)

def getQs(qwords,word):
    for i in range (len(word)-1):
        if ((word[i]=="q") and (word[i+1]!="u")):
            qwords.append(word)
        
print(qu('en.txt'))

col = let2num("q")
row = let2num("u")
probs = prob(A)

print(probs[row,col])

['buqsha', 'buqshas', 'burqa', 'burqas', 'faqir', 'faqirs', 'fiqh', 'fiqhs', 'guqin', 'guqins', 'inqilab', 'inqilabs', 'mbaqanga', 'mbaqangas', 'muqaddam', 'muqaddams', 'niqab', 'niqabs', 'qabala', 'qabalah', 'qabalahs', 'qabalas', 'qabalism', 'qabalisms', 'qabalist', 'qabalistic', 'qabalists', 'qadi', 'qadis', 'qaid', 'qaids', 'qaimaqam', 'qaimaqam', 'qaimaqams', 'qaimaqams', 'qalamdan', 'qalamdans', 'qanat', 'qanats', 'qasida', 'qasidas', 'qat', 'qats', 'qawwal', 'qawwali', 'qawwalis', 'qawwals', 'qi', 'qibla', 'qiblas', 'qigong', 'qigongs', 'qin', 'qindar', 'qindarka', 'qindars', 'qinghaosu', 'qinghaosus', 'qins', 'qintar', 'qintarka', 'qintars', 'qis', 'qiviut', 'qiviuts', 'qoph', 'qophs', 'qorma', 'qormas', 'qwerties', 'qwerty', 'qwertys', 'sheqalim', 'sheqel', 'sheqels', 'suqs', 'talaqs', 'tranqs', 'tsaddiqim', 'tsaddiqs', 'tzaddiqim', 'tzaddiqs', 'umiaqs', 'waqf', 'waqfs', 'yaqona', 'yaqonas']
0.9792560801144492


1. Lastly, write a *namegen(n)* function that generates words of length $n$ using your transition matrix. You may find the following code snippets helpful:
```python
      # This returns a string containing all lowercase letters:
      import string
      string.ascii_lowercase

      # This returns a random number between 0 and 25, with probability distribution given by the vector v:
      np.random.choice(26,p=v)

      # You can add a letter to string as follows:
      mystring = 'co'
      mystring += 'w'
      mystring
```

Test out your code by generating words of different lengths. Are most of them pronounceable? Explain why they are not all pronounceable. 
  
  
**Extra Credit** Write down a few ideas that would increase the likelihood of pronounceable randomly generated words. Implement them in code.

In [15]:
import string
def namegen(n):
    abc = list('abcdefghijklmnopqrstuvwxyz')
    v = np.sum(probs,axis=0)
    v = v/np.sum(v)
    start = abc[np.random.choice(26,p=v)]
    while n>0:
        v = probs[:,let2num(start[-1])]
        next = np.random.choice(26,p=v)
        start += abc[next]
        n-=1
    return(start)
print(namegen(5))

zescti
